version: "3.10"

services:
  pg:
    image: bitnami/postgresql:latest
    container_name: devices-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - devices-volume:/bitnami/postgresql
    networks:
      - devices-network

networks:
  devices-network:
    driver: bridge

volumes:
  devices-volume:
    driver: local
